[package]
name = "tracker"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
chrono = "0.4.43"
clap = { version = "4.4.0", features = ["derive"] }
rusqlite = { version = "0.38.0", features = ["bundled"] }
tracing = "0.1.44"
tracing-subscriber = "0.3.22"
